apiVersion: v1
kind: Service
metadata:
  name: digital-twin-lab
  namespace: digital-twin-simulation-lab
spec:
  selector:
    app: digital-twin-lab
  ports:
    - name: http
      port: 8017
      targetPort: 8017
