apiVersion: v1
kind: Service
metadata:
  name: simulation-api
  namespace: digital-twin-simulation-lab
spec:
  selector:
    app: simulation-api
  ports:
    - name: http
      port: 8017
      targetPort: 8017
